[package]
name = "bigBytes-wasm"
version = "0.1.0"
description = "A sample project sending a big bytes array"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.79"

[build-dependencies]
